name: Buildtest 

on:
  push:
    branches: [ main ]
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build WAR
        run: mvn clean package -DskipTests

      - name: Verify WAR file
        run: ls -l target


      - name: Force failure
        run: exit 1
