name: Deploy to EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest


    env:
      AWS_REGION: us-east-1
      ACCOUNT_ID: ${{ vars.ACCOUNT_ID }}


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List files
        run: |
            pwd
              ls -la
              ls -la k8s
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/githubActionsEks
          aws-region: ${{ env.AWS_REGION }}
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/


